# Generated by Django 2.0.6 on 2018-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20180807_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, verbose_name='username')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sdept', models.CharField(max_length=50, verbose_name='sdept')),
            ],
        ),
        migrations.AlterModelOptions(
            name='workproject',
            options={'verbose_name': '公司项目信息', 'verbose_name_plural': '公司项目信息'},
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='create_time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='regularmeeting',
            name='participant',
            field=models.CharField(max_length=500, verbose_name='参与人员'),
        ),
    ]
