# Generated by Django 2.0.6 on 2018-08-15 07:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20180815_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='report_content',
            field=tinymce.models.HTMLField(verbose_name='日报内容'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, '很差'), (2, '差'), (3, '一般'), (4, '好'), (5, '很好')], null=True, verbose_name='评价等级'),
        ),
    ]
